//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PlcText.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDM_STOPDAEMON                  101
#define IDD_PLCTEXT_DIALOG              102
#define IDR_HTML_DATAVIEWER             103
#define IDR_HTML_DATAVIEWER1            105
#define IDR_HTML_PTZTESTPANEL           106
#define IDR_HTML_PTZTESTPANEL1          108
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     130
#define IDB_BITMAP2                     133
#define IDI_ICON1                       139
#define IDD_DIALOG1                     140
#define IDD_DIALOG_DATAVIEW             141
#define IDD_DIALOG_DATA                 142
#define IDD_DIALOG_TESTPANEL            143
#define IDC_BTN_CONNECT                 1000
#define IDC_BTN_LOGOUT                  1001
#define IDC_EDIT_PORT                   1003
#define IDC_EDIT_PORT2                  1004
#define IDC_EDIT_PORT_SVR               1004
#define IDC_BTN_GETINFO                 1005
#define IDC_EDIT                        1007
#define IDC_IPADDRESS1                  1009
#define IDC_EDIT_RACK                   1010
#define IDC_EDIT_SOLT                   1011
#define IDC_IPADDRESS_SVR               1012
#define IDC_EDIT_GROUPNUM               1012
#define IDC_EDIT_KEYID                  1013
#define IDC_EDIT_SCREENNUM              1013
#define IDC_COM_OFFSET                  1014
#define IDC_EDIT_MODENUM                1014
#define IDC_STATIC_INFO                 1015
#define IDC_EDIT_SWITCHNUM              1015
#define IDC_BUTTON1                     1016
#define IDC_BUTTON2                     1017
#define IDC_BTN_SET                     1017
#define IDC_BUTTON_ADD                  1017
#define IDC_BUTTON_UP_TP                1017
#define IDC_COMBO1                      1018
#define IDC_COMBO_CLEAR                 1018
#define IDC_COMBO_BLOCKID               1018
#define IDC_BUTTON_LEFTUP_TP            1018
#define IDC_EDIT_TIME                   1019
#define IDC_BUTTON_LEFT_TP              1019
#define IDC_EDIT_PRESET                 1020
#define IDC_EDIT_PLCTIMEOUT             1020
#define IDC_BUTTON_STOP_TP              1020
#define IDC_BUTTON3                     1021
#define IDC_BTN_TEXT                    1021
#define IDC_BTN_TEST                    1021
#define IDC_BUTTON_RIGHT_TP             1021
#define IDC_COM_IPC1                    1022
#define IDC_BTN_CLEAN_LOG               1022
#define IDC_BUTTON_LEFTDOWN_TP          1022
#define IDC_COM_IPC2                    1023
#define IDC_BUTTON_DOWN_TP              1023
#define IDC_BTN_DIS                     1024
#define IDC_BUTTON_RIGHTDOWN_TP         1024
#define IDC_EDIT_SCR11                  1025
#define IDC_BUTTON_ZOOM_OUT_TP          1025
#define IDC_EDIT_SCR12                  1026
#define IDC_BUTTON_ZOOM_IN_TP           1026
#define IDC_EDIT_SCR41                  1027
#define IDC_EDIT_SCR42                  1028
#define IDC_EDIT_SCR71                  1029
#define IDC_EDIT_SCR72                  1030
#define IDC_KET                         1031
#define IDC_STATIC_SERVER               1032
#define IDC_RADIO1                      1033
#define IDC_RADIO_BYTE                  1033
#define IDC_RADIO2                      1034
#define IDC_RADIO_WORD                  1034
#define IDC_RADIO3                      1035
#define IDC_RADIO_DWORD                 1035
#define IDC_LIST_LOG                    1039
#define IDC_BUTTON4                     1040
#define IDC_TREE1                       1040
#define IDC_CHECK1                      1041
#define IDC_CHECK_RUN                   1041
#define IDC_CHECK_PTZ                   1041
#define IDC_CHECK_BYTEBIT               1041
#define IDC_CHECK_CONNECTCAM_TP         1041
#define IDC_EDIT_SCR21                  1042
#define IDC_PLC_SET                     1042
#define IDC_LIST_LOG_FILTER             1042
#define IDC_EDIT_SCR31                  1043
#define IDC_STATIC_TEST                 1043
#define IDC_EDIT_SCR22                  1044
#define IDC_STATIC_GROUP_NUM            1044
#define IDC_EDIT_SCR32                  1045
#define IDC_STATIC_SCREEN_NUM           1045
#define IDC_EDIT_SCR51                  1046
#define IDC_STATIC_MODE_NUM             1046
#define IDC_EDIT_SCR52                  1047
#define IDC_STATIC_SWITCH_NUM           1047
#define IDC_EDIT_SCR61                  1048
#define IDC_EDIT_SCR62                  1049
#define IDC_EDIT_SCR81                  1050
#define IDC_EDIT_SCR82                  1051
#define IDC_CHECK_ZOOM                  1051
#define IDC_EDIT_SCREEN17               1052
#define IDC_CHECK_TVWALL                1052
#define IDC_CHECK_ENABLE                1054
#define IDC_CHECK5                      1055
#define IDC_CHECK_SWITCH                1055
#define IDC_CHECK2                      1056
#define IDC_CHECK_LISTSTOP              1056
#define IDC_CHECK_ENABLEWATCHDOG        1056
#define IDC_CHECK3                      1057
#define IDC_EDIT_FILTER                 1058
#define IDC_CHECK4                      1058
#define IDC_CHECK_FILTER                1059
#define IDC_CHECK6                      1059
#define IDC_EDIT_OFFSET                 1060
#define IDC_STATIC_WATCHDOG             1061
#define IDC_CHECK7                      1061
#define IDC_EDIT_DATA                   1062
#define IDC_STATIC_RESTART              1062
#define IDC_STATIC_RESTARTTIME          1063
#define IDC_CHECK8                      1063
#define IDC_STATIC_LOG                  1064
#define IDC_CHECK9                      1064
#define IDC_STATIC_AUTOCLEAR            1065
#define IDC_CHECK10                     1065
#define IDC_STATIC_LOGTYPE              1066
#define IDC_STATIC_PLCHEARTTIMEOUT      1067
#define IDC_STATIC_LANGUAGE             1068
#define IDC_COMBO_LANGUAGE              1069
#define IDC_STATIC_VERSION              1070
#define IDC_LIST_SHOW                   1071
#define IDC_COMBO_DB                    1074
#define IDC_COMBO_TYPE                  1075
#define IDC_STATIC_START                1076
#define IDC_EDIT_START                  1077
#define IDC_EDIT_END                    1078
#define IDC_STATIC_TYPE                 1079
#define IDC_BUTTON_CLEAR                1080
#define IDC_STATIC_END                  1081
#define IDC_BUTTON_DATAVIEWER           1082
#define IDC_BUTTON_GROUP_REFRESH        1083
#define IDC_BUTTON_DATAVIEWER_M         1084
#define IDC_LIST1                       1085
#define IDC_EDIT_GROUP_TP               1086
#define IDC_EDIT_IPCINDEX_TP            1087
#define IDC_STATIC_GROUP_TESTPANEL      1088
#define IDC_STATIC_CAMINDEX_TESTPANEL   1089
#define IDC_BUTTON_RIGHTUP_TP           1090
#define IDC_BTN_PTZTT                   1091
#define IDC_BUTTON_PTZTEST              1091

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
